version: "3.8"

services:
  ##########################################################################################
  #                                                                                        #
  #                                SERVIÇOS COMPLEMENTARES                                 #
  #                                                                                        #
  ##########################################################################################
  
  # REMOVE IMAGENS E CONTÊINERES QUE NÃO ESTÃO EM USO
  cleaner:
    image: alpine:latest
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 32M
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: /bin/sh -c "apk add --no-cache docker-cli && while true; do docker system prune -af --filter 'until=24h'; sleep 3600; done"

  # MONITORA QUANDO UMA NOVA IMAGEM É PUBLICADA NO DOCKER HUB
  watchtower:
    image: containrrr/watchtower
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 32M
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30 --cleanup

  # CONFIGURA O PROXY REVERSO PARA PERMITIR O USO DE SUBDOMÍNIOS NA PORTA 80
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    entrypoint: ["/bin/sh", "-c", "sleep 30 && nginx -g 'daemon off;'"]


  ##########################################################################################
  #                                                                                        #
  #                                  Outras Configurações                                  #
  #                                                                                        #
  ##########################################################################################

volumes:
  volume_compartilhado:
    driver: local

networks:
  my_network:
    driver: overlay
    attachable: true
