version: "3.8"

services:
  ##########################################################################################
  #                                                                                        #
  #                                    SUAS APLICAÇÕES                                     #
  #                                                                                        #
  ##########################################################################################
  
  # App 01
  simple-sum:
      image: ozteps/simple-sum:latest # Substitua "ozteps/simple-sum:latest" pela imagem da sua própria aplicação. Pode ser qualquer imagem do Docker Hub ou de um registro privado.
      deploy:
        replicas: 1 # Define que apenas 1 réplica (contêiner) da aplicação será executada.
        update_config:
          parallelism: 1 # Atualiza 1 contêiner por vez ao fazer o update.
          delay: 10s # Espera 10 segundos entre a atualização de cada contêiner.
        resources:
          limits:
            memory: 32M # Limite de memória para o contêiner. Ajuste conforme a necessidade da sua aplicação.
            # Atenção: definir pouca memória para um serviço que precisa de muita pode fazer o contêiner falhar. 
      ports:
        - "9001:80" # Mapeia a porta 9001 no host para a porta 80 no contêiner, permitindo o acesso à aplicação via http://host:9001.

  # App 02
  

  ##########################################################################################
  #                                                                                        #
  #                                SERVIÇOS COMPLEMENTARES                                 #
  #                                                                                        #
  ##########################################################################################
  
  # REMOVE IMAGENS E CONTÊINERES QUE NÃO ESTÃO EM USO
  cleaner:
    image: alpine:latest
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 32M
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: /bin/sh -c "apk add --no-cache docker-cli && while true; do docker system prune -af --filter 'until=24h'; sleep 3600; done"

  # MONITORA QUANDO UMA NOVA IMAGEM É PUBLICADA NO DOCKER HUB
  watchtower:
    image: containrrr/watchtower
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 32M
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30 --cleanup

  # CONFIGURA O PROXY REVERSO PARA PERMITIR O USO DE SUBDOMÍNIOS NA PORTA 80
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    entrypoint: ["/bin/sh", "-c", "sleep 30 && nginx -g 'daemon off;'"]


  ##########################################################################################
  #                                                                                        #
  #                                  Outras Configurações                                  #
  #                                                                                        #
  ##########################################################################################
