version: "3.8"

services:
  # ---------------------------- CONFIGURE AQUI SUAS APLICAÇÕES ---------------------------- #
  simple-sum:
      image: ozteps/simple-sum:latest # Imagem da sua aplicação no Docker Hub
      deploy:
        replicas: 1
        update_config:
          parallelism: 1
          delay: 10s
        resources:
          limits:
            memory: 32M # Limite de memória para o contêiner, ajuste conforme necessário. Temos 1 GB disponível.
      ports:
        - "9001:80"

  # ---------------------------- SERVIÇOS COMPLEMENTARES ----------------------------------- #

  # REMOVE IMAGENS E CONTÊINERES QUE NÃO ESTÃO EM USO
  cleaner:
    image: alpine:latest
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 32M
    command: /bin/sh -c "apk add --no-cache docker-cli && while true; do docker system prune -af --filter 'until=24h'; sleep 3600; done"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  # MONITORA QUANDO UMA NOVA IMAGEM É PUBLICADA NO DOCKER HUB
  watchtower:
    image: containrrr/watchtower
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 32M
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30 --cleanup
  
  # CONFIGURA O PROXY REVERSO PARA PERMITIR O USO DE SUBDOMÍNIOS NA PORTA 80
  # nginx:
  #   image: nginx:latest
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  #   depends_on:
  #     - certbot
  #   entrypoint: ["/bin/sh", "-c", "sleep 30 && nginx -g 'daemon off;'"]